FROM photon:5.0@sha256:1c4f1a00f97a3d5276c6a4f6e1fe1e4372e5b5c4107e813030f716666dd2fb5a

RUN tdnf install -y shadow >> /dev/null \
    && groupadd -g 999 redis \
    && useradd -u 999 -g 999 -c "Redis Database Server" -d /var/lib/redis -s /sbin/nologin -m redis
RUN tdnf install -y redis && tdnf clean all
